apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-limitclusteradmin
placementRef:
  name: policy-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-limitclusteradmin
    kind: Policy
    apiGroup: policy.open-cluster-management.io