apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: hello-world
  name: hello-world
  namespace: helloworld
spec:
  host: hello-world.apps.ocp4.example.com
  to:
    kind: Service
    name: hello-world
    weight: 100
  wildcardPolicy: None

