apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - application.yaml
  - subscription.yaml
  - placementRule.yaml
namespace: dev-secondary
commonLabels:
  app: dev-secondary