apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - application.yaml
  - placementRule.yaml
  - subscription.yaml

commonLabels:
  app: dev-primary

namespace: dev-primary
