apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: maintanance-groups/dev-primary
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: dev-primary
  name:  dev-primary-subscription
  namespace:  dev-primary
spec:
  channel: acm-config-maint-groups-channel/acm-config-maint-groups-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-primary-placement