apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./mysql
  - ../base/common

# Bring together my SQL and hello world and patch
# Take in helloworld and base common patch the tag patch the placement label
# Define the namespace specific to the maintanance group
namespace: dev-secondary

patches:
- path: placementRule.yaml
  target:
    kind: PlacementRule
- path: subsciption.yaml
  target:
    kind: Subscription