apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-path: git-path
    # apps.open-cluster-management.io/git-tag: current_tag
    apps.open-cluster-management.io/reconcile-option: merge
    apps.open-cluster-management.io/git-branch: acm-policies    
  labels:
    app: application_name
    subscription-type: application
  name: application_name
spec:
  channel: acm-config-maint-groups-channel/acm-config-maint-groups-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: placement_reference
